version: "3.6"
services:
  # We run a full Tezos sandbox network using Flextesa (https://tezos.gitlab.io/flextesa/).
  # The deku-flextesa image has already been pre-populated with a Deku bridge contract
  # configured for these nodes.
  flextesa:
    container_name: deku_flextesa
    # FIXME: publish this image somewhere
    image: ghcr.io/marigold-dev/deku-fextesa:latest
    command: kathmandubox start
    environment:
      - block_time=4
      - flextesa_node_cors_origin=*
    ports:
      - 127.0.0.1:20000:20000
  deku-node-0:
    container_name: deku-node-0
    image: my-sidechain
    environment:
      # A b58-encoded Ed25519 secret used to sign blocks
      - DEKU_SECRET=edsk4UWkJqpZrAm26qvJE8uY9ZFGFqQiFuBcDyEPASXeHxuD68WvvF
      - DEKU_PORT=4440
      # We'll enable the API for a single node on port 8080
      - DEKU_API_ENABLED=true
      - DEKU_API_PORT=8080
    network_mode: "host"
  deku-node-1:
    container_name: deku-node-1
    image: my-sidechain
    environment:
      - DEKU_SECRET=edsk2mbL2Z7bAmRnuYbmsRe8Yu9rgAq1h993SDxoZncmqyMHDECyBa
      - DEKU_PORT=4441
    network_mode: "host" 
  deku-node-2:
    container_name: deku-node-2
    image: my-sidechain
    environment:
      - DEKU_SECRET=edsk3dx8ZfcaBXsuLsk8fawS1qxjHbZtEoEdpAwxhsjmYTQhoEUxFk
      - DEKU_PORT=4442
    network_mode: "host"  
  deku-node-3:
    container_name: deku-node-3
    image: my-sidechain
    environment:
      - DEKU_SECRET=edsk3MwFfcGp5FsZgrX8FGiBiDutX2kfAuPzU6VdZpKYLyDRVPb879
      - DEKU_PORT=4443
    network_mode: "host"  
