apiVersion: v1
kind: Service
metadata:
  name: deku-node-0
  labels:
    app: deku-node
spec:
  ports:
  - port: 4440
    name: http
    protocol: TCP
    targetPort: 4440
  - port: 9000
    name: prometheus
    protocol: TCP
    targetPort: 9000
  - port: 9732
    name: tezos-rpc
    targetPort: 8732
  selector:
    app: deku-node
    statefulset.kubernetes.io/pod-name: deku-node-0
---
apiVersion: v1
kind: Service
metadata:
  name: deku-node-1
  labels:
    app: deku-node
spec:
  ports:
  - port: 4440
    name: http
    protocol: TCP
    targetPort: 4440
  - port: 9000
    name: prometheus
    protocol: TCP
    targetPort: 9000
  - port: 9732
    name: tezos-rpc
    targetPort: 8732
  selector:
    app: deku-node
    statefulset.kubernetes.io/pod-name: deku-node-1
---
apiVersion: v1
kind: Service
metadata:
  name: deku-node-2
  labels:
    app: deku-node
spec:
  ports:
  - port: 4440
    name: http
    protocol: TCP
    targetPort: 4440
  - port: 9000
    name: prometheus
    protocol: TCP
    targetPort: 9000
  - port: 9732
    name: tezos-rpc
    targetPort: 8732
  selector:
    app: deku-node
    statefulset.kubernetes.io/pod-name: deku-node-2
