name: "Build and test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: deku
          authToken: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: Cache nix store
        id: cache-native
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-devshell-${{ hashFiles('flake.lock') }}
      - name: Restore cache
        if: steps.cache-native.outputs.cache-hit == 'true'
        run: |
          for narinfo in ./cache/*.narinfo; do
            path=$(head -n 1 "$narinfo" | awk '{print $2}')
            nix copy --no-check-sigs --from "file://$(pwd)/cache" "$path"
          done
      - name: "Cache prep"
        run: |
          echo $CACHE_PRIV_KEY > ./nix-cache-key.sec
          sudo mv ./nix-cache-key.sec /etc/nix/nix-cache-key.sec
          ./.github/workflows/list-nix-store.sh > ~/.nix-store-paths
        env:
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}
      # Broken because we patch nixpkgs, can add it back when janestreet 0.15 is added upstream
      # - name: "Run nix flake check"
      #   run: nix flake check
      - name: "Check formatting"
        run: |
          nix fmt -- --no-cache
          if [[ -n "$(git status --porcelain -unormal)" ]]; then
            echo "-----------------------------"
            echo "ERROR: The project is dirty!"
            echo "-----------------------------"
            git status -unormal
            exit 1
          else
            echo "--------------"
            echo "OK: All good!"
            echo "--------------"
          fi
      - name: "Check shell formatting"
        run: nix develop -c shellcheck *.sh
      - name: "Run tests"
        run: nix develop -c dune build @check @runtest --force --no-buffer
      - name: "Build deku via flakes"
        run: nix build --verbose .#deku

      # Includes all our e2e tests
      - name: "tilt ci"
        run: "nix develop -c tilt ci"
      - name: Upload to cache
        run: ./.github/workflows/upload-to-cache.sh

  # Static and docker are linked because we're using the static build in docker
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: deku
          authToken: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: Cache nix store
        id: cache-native
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-devshell-${{ hashFiles('flake.lock') }}
      - name: Restore cache
        if: steps.cache-native.outputs.cache-hit == 'true'
        run: |
          for narinfo in ./cache/*.narinfo; do
            path=$(head -n 1 "$narinfo" | awk '{print $2}')
            nix copy --no-check-sigs --from "file://$(pwd)/cache" "$path"
          done
      - name: "Cache prep"
        run: |
          echo $CACHE_PRIV_KEY > ./nix-cache-key.sec
          sudo mv ./nix-cache-key.sec /etc/nix/nix-cache-key.sec
          ./.github/workflows/list-nix-store.sh > ~/.nix-store-paths
        env:
          CACHE_PRIV_KEY: ${{ secrets.CACHE_PRIV_KEY }}

      - name: "Build static deku via flakes"
        run: nix build --verbose .#deku-static

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%d)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Build docker image"
        run: nix build .#docker
      - name: "Load docker image"
        run: docker load < ./result
      - name: "Re-tag image"
        run: |
          docker image tag ghcr.io/marigold-dev/deku:latest ghcr.io/marigold-dev/deku:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
          docker image tag ghcr.io/marigold-dev/deku:latest ghcr.io/marigold-dev/deku:pr-${{ github.event.number }}-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
      - name: "Push image"
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: |
          docker image push ghcr.io/marigold-dev/deku:latest
          docker image push ghcr.io/marigold-dev/deku:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
      - name: "Push image for PR"
        # Run this if the PR has the "docker" label
        if: contains(github.event.pull_request.labels.*.name, 'docker')
        run: |
          docker image push ghcr.io/marigold-dev/deku:pr-${{ github.event.number }}-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
      - name: Upload to cache
        run: ./.github/workflows/upload-to-cache.sh
