name: Deku Test Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests

    strategy:
      matrix:
        system: [ubuntu]

    runs-on: ${{ matrix.system }}-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
